"""AI-generated alternative (Part D) - beginner-friendly, no database, no GUI.
Generated by Claude; reviewed and tested by the student (see ai_usage.md)."""

appointments = []


def add_appointment(patient_name, practitioner_name, appointment_time):
    """Store one appointment as a dictionary and return it."""
    appointment = {
        "patient_name": patient_name,
        "practitioner_name": practitioner_name,
        "appointment_time": appointment_time,
    }
    appointments.append(appointment)
    return appointment


if __name__ == "__main__":
    add_appointment("Alice Smith", "Dr. John Doe", "2024-07-20 10:00 AM")
    print(appointments)
